# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "jr-balance-app"
    dynamodb_table = "jr-balance-app"
    encrypt        = true
    key            = "terraform.tfstate"
    region         = "us-east-1"
  }
}
